fix: resolve Jackson JR record deserialization issue and remove manua…
Giovds/outdated-maven-plugin pull request #62
Opened 2024-10-05 06:49 UTC by RomeoIndiaJulietUniform

### Overview
This pull request addresses the issue related to Jackson JR record deserialization in the `QueryClient` class.

### Changes Made
- Removed manual mapping for the `FoundDependency` record due to the availability of built-in record deserialization in Jackson JR version 2.18.
- Updated the `FoundDependency` record to utilize direct deserialization from the response.
- Fixed issues related to variable assignment in the `FoundDependency` record constructor.

### Testing
- Unit tests have been updated to verify the functionality of record deserialization.
- All tests pass successfully.

### Related Issues
This pull request closes issues: 
- #60 

Pls let me know if I can improve anywhere or do something more 🙂

2024-10-05 10:13 UTC, Giovds requested changes
Thank you for your pull request and for taking the time to work on this issue! I’ve reviewed the changes, and it seems that the issue is not fully resolved yet. 

Specifically, the current changes are moving the mapping from one method to another. Notice how it is still manually mapping the JSON fields to the correct record fields via casting and calling the `.get()` methods.

I would prefer to let the jackson library handle this logic, so that this code only uses something like `JSON.std.fromBean(Response.class, input)`.

2024-10-05 15:41 UTC, RomeoIndiaJulietUniform commented
Hii @Giovds , see I tried to do that through Jackson after I raised my PR so that I can update it. But the json has some fields defined , specially there is a LocalDate Generic that is defined in the code and Jackson is not letting it pass through so the Unit Test is getting failed, I have tried mulitple ways but not getting any movement. 

One way is to Convert the LocalDate Generic to String for the Timestamp and resolve all its dependenices. I will provide the code below .

public record FoundDependency(String id, String g, String a, String v, LocalDate timestamp) {
    }

    static FoundDependency mapToSearch(final Map<String, Object> doc) {
        try {
            String jsonString = JSON.std.asString(doc);
            return JSON.std.beanFrom(FoundDependency.class, jsonString);
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }      

Do you like to comment on this may be resolved and I really want to work on this issue

2024-10-09 21:55 UTC, RomeoIndiaJulietUniform commented
Thanks for the update!  I’ll keep an eye on the progress of the fix, and once it’s resolved. I will simply update the PR

2024-10-29 08:34 UTC, Giovds commented
@RomeoIndiaJulietUniform I expect this to be solved in the latest version (2.18.1). The project has just been updated, feel free to update the PR.

2024-10-29 22:05 UTC, RomeoIndiaJulietUniform commented
Hii @Giovds , I checked it the issue still exist for handling long timestamp. I have update the PR with the jackson desterilization and commented the part of the code, as it is breaking the tests.  I am attaching the error log for better understanding 

```
Caused by: java.io.IOException: Cannot access field dateTime of record class com.giovds.dto.DependencyResponse
        at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:966)
        at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:133)
        at com.giovds.QueryClient.search(QueryClient.java:54)
        ... 4 more
Caused by: java.lang.IllegalStateException: Cannot access field dateTime of record class com.giovds.dto.DependencyResponse
        at com.fasterxml.jackson.jr.ob.impl.ValueReaderLocator._resolveBeanForDeser(ValueReaderLocator.java)
        at com.fasterxml.jackson.jr.ob.impl.ValueReaderLocator.beanReader(ValueReaderLocator.java)
        at com.fasterxml.jackson.jr.ob.impl.ValueReaderLocator._createReader(ValueReaderLocator.java)
        at com.fasterxml.jackson.jr.ob.impl.ValueReaderLocator.createReader(ValueReaderLocator.java)
        at com.fasterxml.jackson.jr.ob.impl.ValueReaderLocator.findReader(ValueReaderLocator.java)
        at com.fasterxml.jackson.jr.ob.impl.JSONReader.readBean(JSONReader.java)
        at com.fasterxml.jackson.jr.ob.JSON.beanFrom(JSON.java)

```

Please feel free to tell me if anything I missed or needed to be done on my end :)

2024-10-29 22:48 UTC, Giovds commented
This is actually due to the fact that the record now has an instance method (`getDateTime()`) which apparently is seen as deserialisation field by Jackson-JR.  If you make it a static method, or move it to a different class I expect the deserialisation to work.

2024-10-30 04:03 UTC, RomeoIndiaJulietUniform commented
Hii @Giovds , thanks a lot for the suggestions regarding static type conversion in Jackson 🙂. I have updated the PR , all the test cases are passing after the automatic mapping done through jackson.

![Screenshot from 2024-10-30 09-29-46](https://github.com/user-attachments/assets/efed3c04-321d-4c55-bb5d-9b30793f2d53)

Let me know if there's anything else you need me to do.

2024-10-31 17:10 UTC, Giovds approved these changes
I've changed the implementation slightly to use records for the entire request mapping removing all the manual mapping. If you'd like you can take a look at the last commit. Thank you for your contribution!

2024-10-31 17:11 UTC, merged

2024-10-31 20:37 UTC, RomeoIndiaJulietUniform commented
@Giovds Thanks a lot for letting me work on this issue. I learned a lot in the process, and it was a great project to contribute to! :)